// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://fk3zvyxnyje2zlmecey3w4ubcu.appsync-api.us-west-2.amazonaws.com/graphql',
          region: 'us-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-iboh2su4pzavnnsf3h3mwhy3qm'
        }
    }
};

export default config;


