CREATE TABLE "rental_applications" (
	"id" serial PRIMARY KEY NOT NULL,
	"applicant_id" uuid NOT NULL,
	"application_date" timestamp DEFAULT now(),
	"building_address" text NOT NULL,
	"apartment_number" text NOT NULL,
	"move_in_date" timestamp NOT NULL,
	"monthly_rent" real NOT NULL,
	"apartment_type" text NOT NULL,
	"how_did_you_hear" text,
	"applicant_name" text NOT NULL,
	"applicant_dob" timestamp NOT NULL,
	"applicant_ssn" text,
	"applicant_phone" text,
	"applicant_email" text NOT NULL,
	"applicant_license" text,
	"applicant_license_state" text,
	"applicant_address" text NOT NULL,
	"applicant_city" text NOT NULL,
	"applicant_state" text NOT NULL,
	"applicant_zip" text NOT NULL,
	"applicant_length_at_address" text,
	"applicant_landlord_name" text,
	"applicant_current_rent" real,
	"applicant_reason_for_moving" text,
	"applicant_employer" text,
	"applicant_position" text,
	"applicant_employment_start" timestamp,
	"applicant_income" real,
	"applicant_other_income" real,
	"applicant_other_income_source" text,
	"applicant_bank_name" text,
	"applicant_account_type" text,
	"has_co_applicant" boolean DEFAULT false,
	"co_applicant_name" text,
	"co_applicant_relationship" text,
	"co_applicant_dob" timestamp,
	"co_applicant_ssn" text,
	"co_applicant_phone" text,
	"co_applicant_email" text,
	"co_applicant_same_address" boolean DEFAULT false,
	"co_applicant_address" text,
	"co_applicant_city" text,
	"co_applicant_state" text,
	"co_applicant_zip" text,
	"co_applicant_length_at_address" text,
	"co_applicant_employer" text,
	"co_applicant_position" text,
	"co_applicant_employment_start" timestamp,
	"co_applicant_income" real,
	"co_applicant_other_income" real,
	"co_applicant_bank_name" text,
	"co_applicant_account_type" text,
	"has_guarantor" boolean DEFAULT false,
	"guarantor_name" text,
	"guarantor_relationship" text,
	"guarantor_dob" timestamp,
	"guarantor_ssn" text,
	"guarantor_phone" text,
	"guarantor_email" text,
	"guarantor_address" text,
	"guarantor_city" text,
	"guarantor_state" text,
	"guarantor_zip" text,
	"guarantor_length_at_address" text,
	"guarantor_employer" text,
	"guarantor_position" text,
	"guarantor_employment_start" timestamp,
	"guarantor_income" real,
	"guarantor_other_income" real,
	"guarantor_bank_name" text,
	"guarantor_account_type" text,
	"applicant_signature" text,
	"co_applicant_signature" text,
	"guarantor_signature" text,
	"has_bankruptcy" boolean DEFAULT false,
	"bankruptcy_details" text,
	"has_eviction" boolean DEFAULT false,
	"eviction_details" text,
	"has_criminal_history" boolean DEFAULT false,
	"criminal_history_details" text,
	"has_pets" boolean DEFAULT false,
	"pet_details" text,
	"smoking_status" text,
	"documents" text,
	"encrypted_data" text,
	"status" text DEFAULT 'draft',
	"submitted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"applicant_id" uuid NOT NULL,
	"cognito_username" text NOT NULL,
	"email" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"phone_number" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_applicant_id_unique" UNIQUE("applicant_id"),
	CONSTRAINT "users_cognito_username_unique" UNIQUE("cognito_username")
);
--> statement-breakpoint
ALTER TABLE "rental_applications" ADD CONSTRAINT "rental_applications_applicant_id_users_applicant_id_fk" FOREIGN KEY ("applicant_id") REFERENCES "public"."users"("applicant_id") ON DELETE no action ON UPDATE no action;