-- Migration to update rental_applications table for new nested structure
-- Drop old columns and add new JSON-based structure

-- First, add new columns
ALTER TABLE "rental_applications" ADD COLUMN "application" text;
ALTER TABLE "rental_applications" ADD COLUMN "applicant" text;
ALTER TABLE "rental_applications" ADD COLUMN "co_applicant" text;
ALTER TABLE "rental_applications" ADD COLUMN "guarantor" text;
ALTER TABLE "rental_applications" ADD COLUMN "occupants" text;
ALTER TABLE "rental_applications" ADD COLUMN "application_id" text;
ALTER TABLE "rental_applications" ADD COLUMN "zoneinfo" text;
ALTER TABLE "rental_applications" ADD COLUMN "webhook_summary" text;

-- Drop old columns (after adding new ones to preserve data)
ALTER TABLE "rental_applications" DROP COLUMN "application_date";
ALTER TABLE "rental_applications" DROP COLUMN "building_address";
ALTER TABLE "rental_applications" DROP COLUMN "apartment_number";
ALTER TABLE "rental_applications" DROP COLUMN "move_in_date";
ALTER TABLE "rental_applications" DROP COLUMN "monthly_rent";
ALTER TABLE "rental_applications" DROP COLUMN "apartment_type";
ALTER TABLE "rental_applications" DROP COLUMN "how_did_you_hear";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_dob";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_ssn";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_phone";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_license";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_license_state";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_address";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_city";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_state";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_zip";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_length_at_address";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_landlord_name";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_current_rent";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_reason_for_moving";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_employer";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_position";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_employment_start";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_income";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_other_income";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_other_income_source";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_bank_name";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_account_type";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_name";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_relationship";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_dob";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_ssn";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_phone";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_email";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_same_address";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_address";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_city";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_state";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_zip";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_length_at_address";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_employer";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_position";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_employment_start";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_income";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_other_income";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_bank_name";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_account_type";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_name";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_relationship";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_dob";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_ssn";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_phone";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_email";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_address";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_city";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_state";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_zip";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_length_at_address";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_employer";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_position";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_employment_start";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_income";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_other_income";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_bank_name";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_account_type";
ALTER TABLE "rental_applications" DROP COLUMN "applicant_signature";
ALTER TABLE "rental_applications" DROP COLUMN "co_applicant_signature";
ALTER TABLE "rental_applications" DROP COLUMN "guarantor_signature";
ALTER TABLE "rental_applications" DROP COLUMN "has_bankruptcy";
ALTER TABLE "rental_applications" DROP COLUMN "bankruptcy_details";
ALTER TABLE "rental_applications" DROP COLUMN "has_eviction";
ALTER TABLE "rental_applications" DROP COLUMN "eviction_details";
ALTER TABLE "rental_applications" DROP COLUMN "has_criminal_history";
ALTER TABLE "rental_applications" DROP COLUMN "criminal_history_details";
ALTER TABLE "rental_applications" DROP COLUMN "has_pets";
ALTER TABLE "rental_applications" DROP COLUMN "pet_details";
ALTER TABLE "rental_applications" DROP COLUMN "smoking_status";
