import React from 'react';
import { PropertyAmenitiesMap } from '@/components/property-amenities-map';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { 
  Sparkles, 
  MapPin, 
  Utensils, 
  ShoppingBag, 
  GraduationCap, 
  Bus, 
  TreePine, 
  Building2,
  ArrowLeft,
  Zap,
  Brain,
  MessageSquare
} from 'lucide-react';
import { useLocation } from 'wouter';

export default function AmenitiesDemoPage() {
  const [, setLocation] = useLocation();
  
  // Demo coordinates for different locations
  const demoLocations = [
    {
      name: 'Manhattan Luxury Apartment',
      coordinates: [40.7589, -73.9851] as [number, number],
      description: 'Prime location in the heart of Manhattan'
    },
    {
      name: 'Brooklyn Heights Townhouse',
      coordinates: [40.6955, -73.9939] as [number, number],
      description: 'Charming townhouse in historic Brooklyn Heights'
    },
    {
      name: 'Queens Modern Complex',
      coordinates: [40.7505, -73.9934] as [number, number],
      description: 'Contemporary living in vibrant Queens'
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <div className="mb-8">
          <Button 
            variant="ghost" 
            onClick={() => setLocation('/')}
            className="mb-4 hover:bg-gray-100"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
          
          <div className="text-center">
            <div className="flex items-center justify-center gap-3 mb-4">
              <div className="p-3 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full">
                <Sparkles className="w-8 h-8 text-white" />
              </div>
              <h1 className="text-4xl font-bold text-gray-900">AI-Powered Amenities Map</h1>
            </div>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Experience the future of property exploration with Gemini AI-generated descriptions, 
              dynamic captions, and intelligent amenity insights
            </p>
          </div>
        </div>

        {/* AI Features Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <Card className="text-center p-6 hover:shadow-lg transition-shadow">
            <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center mx-auto mb-4">
              <Brain className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-3">AI-Generated Descriptions</h3>
            <p className="text-gray-600">
              Each amenity gets a unique, compelling description generated by Gemini AI, 
              highlighting what makes each location special
            </p>
          </Card>

          <Card className="text-center p-6 hover:shadow-lg transition-shadow">
            <div className="w-16 h-16 bg-gradient-to-r from-green-500 to-blue-500 rounded-full flex items-center justify-center mx-auto mb-4">
              <MessageSquare className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Dynamic Location Captions</h3>
            <p className="text-gray-600">
              Intelligent captions that adapt to each property, emphasizing location benefits 
              and nearby amenity counts
            </p>
          </Card>

          <Card className="text-center p-6 hover:shadow-lg transition-shadow">
            <div className="w-16 h-16 bg-gradient-to-r from-orange-500 to-red-500 rounded-full flex items-center justify-center mx-auto mb-4">
              <Zap className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-3">Real-time Regeneration</h3>
            <p className="text-gray-600">
              Click "Regenerate AI" to get fresh, unique descriptions and captions 
              for every viewing experience
            </p>
          </Card>
        </div>

        {/* Demo Properties */}
        <div className="space-y-12">
          {demoLocations.map((location, index) => (
            <div key={index}>
              <div className="text-center mb-6">
                <h2 className="text-2xl font-bold text-gray-900 mb-2">{location.name}</h2>
                <p className="text-gray-600">{location.description}</p>
                <div className="flex items-center justify-center gap-2 mt-3">
                  <MapPin className="w-4 h-4 text-red-500" />
                  <span className="text-sm text-gray-500">
                    {location.coordinates[0].toFixed(4)}, {location.coordinates[1].toFixed(4)}
                  </span>
                </div>
              </div>

              <PropertyAmenitiesMap
                propertyName={location.name}
                propertyCoordinates={location.coordinates}
                className="mb-8"
              />

              {index < demoLocations.length - 1 && <Separator className="my-8" />}
            </div>
          ))}
        </div>

        {/* How It Works */}
        <Card className="mt-16">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-center flex items-center justify-center gap-3">
              <Sparkles className="w-6 h-6 text-purple-600" />
              How the AI Integration Works
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <h4 className="font-semibold text-lg mb-4 text-gray-900">1. Data Collection</h4>
                <div className="space-y-3 text-sm text-gray-600">
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Property coordinates and basic amenity information are collected</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Nearby facilities are identified within walking distance</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Distance calculations and ratings are processed</p>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-semibold text-lg mb-4 text-gray-900">2. AI Generation</h4>
                <div className="space-y-3 text-sm text-gray-600">
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Gemini AI creates unique descriptions for each amenity</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Location-specific captions are generated dynamically</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Content is optimized for engagement and conversion</p>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-semibold text-lg mb-4 text-gray-900">3. Interactive Display</h4>
                <div className="space-y-3 text-sm text-gray-600">
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-purple-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>AI-generated content is displayed in beautiful amenity cards</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-purple-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Interactive map shows all amenities with detailed popups</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-purple-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Users can regenerate content for fresh perspectives</p>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-semibold text-lg mb-4 text-gray-900">4. User Experience</h4>
                <div className="space-y-3 text-sm text-gray-600">
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Filter amenities by type (restaurants, shopping, schools, etc.)</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>View walking distance radius for convenience assessment</p>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p>Get AI-powered insights into location benefits</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Amenity Categories */}
        <Card className="mt-8">
          <CardHeader>
            <CardTitle className="text-xl font-semibold text-center">Amenity Categories</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              <div className="flex items-center gap-3 p-3 bg-orange-50 rounded-lg border border-orange-200">
                <div className="w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center">
                  <Utensils className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Restaurants</p>
                  <p className="text-xs text-gray-600">Dining & Entertainment</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-blue-50 rounded-lg border border-blue-200">
                <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                  <ShoppingBag className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Shopping</p>
                  <p className="text-xs text-gray-600">Retail & Services</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-green-50 rounded-lg border border-green-200">
                <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                  <GraduationCap className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Schools</p>
                  <p className="text-xs text-gray-600">Education & Learning</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-purple-50 rounded-lg border border-purple-200">
                <div className="w-8 h-8 bg-purple-500 rounded-full flex items-center justify-center">
                  <Bus className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Transportation</p>
                  <p className="text-xs text-gray-600">Transit & Parking</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-emerald-50 rounded-lg border border-emerald-200">
                <div className="w-8 h-8 bg-emerald-500 rounded-full flex items-center justify-center">
                  <TreePine className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Parks</p>
                  <p className="text-xs text-gray-600">Recreation & Nature</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-red-50 rounded-lg border border-red-200">
                <div className="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                  <Building2 className="w-4 h-4 text-white" />
                </div>
                <div>
                  <p className="font-medium text-gray-900">Healthcare</p>
                  <p className="text-xs text-gray-600">Medical & Wellness</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Call to Action */}
        <div className="text-center mt-12">
          <Card className="bg-gradient-to-r from-blue-50 to-purple-50 border-blue-200">
            <CardContent className="p-8">
              <h3 className="text-2xl font-bold text-gray-900 mb-4">
                Ready to Experience AI-Powered Property Exploration?
              </h3>
              <p className="text-gray-600 mb-6 max-w-2xl mx-auto">
                The amenities map feature is now integrated into all property detail pages, 
                providing intelligent insights and engaging descriptions powered by Gemini AI.
              </p>
              <div className="flex gap-4 justify-center">
                <Button 
                  onClick={() => setLocation('/')}
                  className="bg-blue-600 hover:bg-blue-700"
                >
                  Explore Properties
                </Button>
                <Button 
                  variant="outline"
                  onClick={() => window.open('https://generativelanguage.googleapis.com/', '_blank')}
                >
                  Learn About Gemini AI
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
